#!/bin/sh


option=$(echo $1 | egrep '\-\-')
case $option in
	"--list")
		case $2 in
			"")	awk 'BEGIN{print "ID\tDataset\t\tTime"} {print NR "\t" $1 "\t\t" $2 " " $3}' ./.list
				;;
			*)	awk 'BEGIN{print "ID\tDataset\t\tTime"} /^'"$2"'/{print NR "\t" $1 "\t\t" $2 " " $3}' ./.list
				;;
		esac
		;;
	"--delete")
		case $2 in
			"")	echo "please enter snapshot name or ID"
				;;
			*)	n=$(echo $2 | egrep -o '\S*')
				case $n in
					*)	res=$(cat ./.list | egrep -o '\S*')
						case $res in
							'')	echo "the list is empty"
								;;
							*)	x=$(echo $2 | egrep '[0-9]*')
									num=$(awk '/\S*/{sum++} END{print sum}' ./.list)
									i=0
									while [ ${i} -lt ${num} ] 
									do
										snap=$(awk -v n=$n 'BEGIN{num=0}/^'"$n"'/{if(num==0){print $1;num++}}' ./.list)
										d=$(awk -v n=$n 'BEGIN{num=0}/^'"$n"'/{if(num==0){print $2;num++}}' ./.list)
										TIME=$(awk -v n=$n 'BEGIN{num=0}/^'"$n"'/{if(num==0){print $3;num++}}' ./.list)
										sudo zfs destroy "${snap}@${d}_${TIME}"
										awk -v n=$n 'BEGIN{num=0} {if($1==n && num==0){num++}else{print}}' ./.list > .tmp
										cat .tmp > ./.list
										rm .tmp
										i=$((i+1))
									done
									;;
						esac
						;;
					"")	echo "please enter the snapshot name"
						;;
				esac
				;;
		esac
		;;
	"")	dataset=$(echo $1 | awk '/\S*/{print}')
		case $dataset in
			"")	echo "please enter the dataset name"
				;;
			*)	D=$(date +"%Y-%m-%d %T")
				time=$(date +"%Y-%m-%d_%T")
				i=0
				sudo zfs snapshot "${dataset}@${time}"
				res=$?
				case $res in
					0)	echo -e "${dataset}\t${D}" >> ./.list
						;;
				esac
				rotation=$(echo $2 | awk '/^[0-9]*$/{print}')
				if [ -z "${rotation}" ] || [ ${rotation} -ge 30 ];then
					rotation=30
				fi
				num=$(cat ./.list | awk 'BEGIN{sum=0} /^'"$dataset"'/{sum++} END{print sum}')
				if [ ${num} -ge ${rotation} ];then
					de=$num-$rotation
						snap=$(awk 'BEGIN{n=0} /^'"$dataset"'/{if(n==0){print $1;n++}}' ./.list)
						d=$(awk 'BEGIN{n=0} /^'"$dataset"'/{if(n==0){print $2;n++}}' ./.list)
						TIME=$(awk 'BEGIN{n=0} /^'"$dataset"'/{if(n==0){print $3;n++}}' ./.list)
						sudo zfs destroy "${snap}@${d} ${TIME}"
						awk 'BEGIN{n=0} /^'"$dataset"'/{if(n==0){n++}else{print}}' ./.list > .tmp
						cat .tmp > ./.list
						rm .tmp
						i=$((${i}+1))
					done
				fi
				;;
		esac
		;;
	*)	echo "unknow option"
		;;
esac
